In [1]:
import numpy as np

### Projection matrix

In [3]:
A = np.array([[1,0],[0,0]])
A

array([[1, 0],
       [0, 0]])

### Eigenvalue, Eigenvactor

In [5]:
D, V = np.linalg.eig(A)
print(D)
print(V)

[1. 0.]
[[1. 0.]
 [0. 1.]]


# System of Linear Equation

In [6]:
X = np.matrix([[1],[0]])
Y = np.matrix([[2],[0]])

print(X)
print(Y)

[[1]
 [0]]
[[2]
 [0]]


In [7]:
X.T*Y

matrix([[2]])

In [9]:
Y.T*Y

matrix([[4]])

In [12]:
omega = (X.T*Y)/(Y.T*Y)
omega = float(omega)

In [14]:
W = omega * Y
W

matrix([[1.],
        [0.]])

In [17]:
A = np.matrix([[1,0],
               [0,1],
               [0,0]])
B = np.matrix([[1],[1],[1]])

X = (A.T * A).T * A.T * B
print(X)
B_star = A*X
print(B_star)

[[1]
 [1]]
[[1]
 [1]
 [0]]
